
name: Build and Deploy

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - playroom

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build-and-deploy:
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      # Runs the Super-Linter action
      - name: Install and Build ðŸ”§
        run: |
          yarn --frozen-lockfile
          yarn playroom:build
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages-playroom # The branch the action should deploy to.
          FOLDER: playroom/dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch